### ISSUE TITLE
How to serve data to component?

### ISSUE THREAD

**Issue by liming** [keystonejs/universal-keystone-boilerplate#76]
I like the idea in this boilerplate and tried it for my website. But I could not find a proper way to pass the data from DB to react component.

Take the team example, how to get the teams list from DB and feed it to team component?

I know there will be a redux solution in future: https://github.com/keystonejs/keystone/issues/2090

But do we have another choice before that? 

Thanks!

**Comment by LorbusChris** [comment]
This boilerplate is currently a WIP. It will use this to serve data through redux:

[react-easy-universal](https://github.com/keystonejs/react-easy-universal)

Feel free to submit a PR :)

**Comment by ericelliott** [comment]
:+1:

**Comment by liming** [comment]
Thanks guys. I will keep an eye on this. It's really a great move of keystonejs. Hope can see it soon.
